### ISSUE TITLE
Feature Request: Keywords

### ISSUE THREAD

**Issue by ttufts** [NicoSantangelo/hangouts-chrome-notifications#3]
I've been trying to find a way to get keyword notifications in hangouts, I think this plugin might be a good starting point. 

Does this plugin have the ability to scan the content of new messages in Hangouts? If so, it should be trivially easy to add a list of keywords to watch for, then scan the content of any new messages for those keywords. 

I want to be able to mute group hangouts, but get a notification if my name is mentioned. I use this in Skype all the time and Hangouts still doesn't have it (though there was an open feature request for it in 2015). 

Thoughts? Glad to help where I can.

**Comment by nicosantangelo** [comment]
Hey! This totally doable. The extension just forwards the chat text to a notification, but it _can_ check for keywords before doing so.
Furthermore, it already has a similar feature:

![image](https://user-images.githubusercontent.com/692077/35437671-c67dc7d8-0293-11e8-8af2-1c53c19a7c29.png)

which is implemented [here](https://github.com/NicoSantangelo/hangouts-chrome-notifications/blob/master/configuration.js#L7) and [here](https://github.com/NicoSantangelo/hangouts-chrome-notifications/blob/master/background.js#L29). Adding keyword filtering following that implementation should be easy enough.

I think it's a good feature to have, but I've been reluctant to update the extension because it already has 70k+ users and the Webstore update system is really bad. To update the extension without people thinking it broke, I have to open a tab with a message alerting the user of the update and asking for a page refresh.

I'll try to find a better way to do the update. Even if I don't find it, if you want to work on this as a PR, I can give you a hand and so you can later use your code instead of the webstore extension.

**Comment by nicosantangelo** [comment]
@ttufts Hey there, I ended up adding this. It's already published if you want to give it a try, from version 3.0.0

Thanks for the suggestion!

**Comment by ttufts** [comment]
Gave it a try; it's sweet! Thanks for adding the feature!!
